---
name: Publican
version: 2.1
author:
  - 'Jeff Fearn <jfearn@redhat.com>'
abstract: a DocBook XML publishing tool.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Archive::Tar: 0
  Archive::Zip: 0
  Carp: 0
  Config::Simple: 0
  Cwd: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Dumper: 0
  DateTime: 0
  DateTime::Format::DateParse: 0
  Encode: 0
  File::Basename: 0
  File::Copy::Recursive: 0.38
  File::Find: 0
  File::Find::Rule: 0
  File::Path: 0
  File::Spec: 0
  File::pushd: 0
  Getopt::Long: 0
  HTML::FormatText: 0
  HTML::TreeBuilder: 0
  I18N::LangTags::List: 0
  IO::String: 0
  Image::Magick: 0
  Image::Size: 0
  Locale::Language: 0
  Locale::Maketext::Gettext: 0
  Locale::PO: 0
  Makefile::Parser: 0
  Syntax::Highlight::Engine::Kate: 0
  Template: 0
  Term::ANSIColor: 0
  Text::Wrap: 0
  XML::LibXML: 1.67
  XML::LibXSLT: 1.67
  XML::TreeBuilder: 3.09
  version: 0
build_requires:
  Archive::Tar: 0
  Archive::Zip: 0
  Carp: 0
  Config::Simple: 0
  Cwd: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Dumper: 0
  DateTime: 0
  DateTime::Format::DateParse: 0
  Devel::Cover: 0
  Encode: 0
  File::Basename: 0
  File::Copy::Recursive: 0.38
  File::Find: 0
  File::Find::Rule: 0
  File::Path: 0
  File::Spec: 0
  File::pushd: 0
  Getopt::Long: 0
  HTML::FormatText: 0
  HTML::TreeBuilder: 0
  I18N::LangTags::List: 0
  IO::String: 0
  Image::Magick: 0
  Image::Size: 0
  Locale::Language: 0
  Locale::Maketext::Gettext: 0
  Locale::PO: 0
  Makefile::Parser: 0
  Module::Build: 0
  Syntax::Highlight::Engine::Kate: 0
  Template: 0
  Term::ANSIColor: 0
  Test::Exception: 0
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Text::Wrap: 0
  XML::LibXML: 1.67
  XML::LibXSLT: 1.67
  XML::TreeBuilder: 3.09
  version: 0
provides:
  Publican:
    file: lib/Publican.pm
    version: 2.1
  Publican::Builder:
    file: lib/Publican/Builder.pm
    version: 0.2
  Publican::CreateBook:
    file: lib/Publican/CreateBook.pm
    version: 0.2
  Publican::CreateBrand:
    file: lib/Publican/CreateBrand.pm
    version: 0.2
  Publican::Localise:
    file: lib/Publican/Localise.pm
  Publican::Localise::C:
    file: lib/Publican/Localise.pm
  Publican::Localise::as:
    file: lib/Publican/Localise.pm
  Publican::Localise::bg:
    file: lib/Publican/Localise.pm
  Publican::Localise::bn_in:
    file: lib/Publican/Localise.pm
  Publican::Localise::bs:
    file: lib/Publican/Localise.pm
  Publican::Localise::ca:
    file: lib/Publican/Localise.pm
  Publican::Localise::cs:
    file: lib/Publican/Localise.pm
  Publican::Localise::da:
    file: lib/Publican/Localise.pm
  Publican::Localise::de:
    file: lib/Publican/Localise.pm
  Publican::Localise::el:
    file: lib/Publican/Localise.pm
  Publican::Localise::en:
    file: lib/Publican/Localise.pm
  Publican::Localise::es:
    file: lib/Publican/Localise.pm
  Publican::Localise::fi:
    file: lib/Publican/Localise.pm
  Publican::Localise::fr:
    file: lib/Publican/Localise.pm
  Publican::Localise::gu:
    file: lib/Publican/Localise.pm
  Publican::Localise::he:
    file: lib/Publican/Localise.pm
  Publican::Localise::hi:
    file: lib/Publican/Localise.pm
  Publican::Localise::hr:
    file: lib/Publican/Localise.pm
  Publican::Localise::hu:
    file: lib/Publican/Localise.pm
  Publican::Localise::id:
    file: lib/Publican/Localise.pm
  Publican::Localise::it:
    file: lib/Publican/Localise.pm
  Publican::Localise::ja:
    file: lib/Publican/Localise.pm
  Publican::Localise::kn:
    file: lib/Publican/Localise.pm
  Publican::Localise::ko:
    file: lib/Publican/Localise.pm
  Publican::Localise::lv:
    file: lib/Publican/Localise.pm
  Publican::Localise::ml:
    file: lib/Publican/Localise.pm
  Publican::Localise::mr:
    file: lib/Publican/Localise.pm
  Publican::Localise::ms:
    file: lib/Publican/Localise.pm
  Publican::Localise::nb:
    file: lib/Publican/Localise.pm
  Publican::Localise::nl:
    file: lib/Publican/Localise.pm
  Publican::Localise::or:
    file: lib/Publican/Localise.pm
  Publican::Localise::pa:
    file: lib/Publican/Localise.pm
  Publican::Localise::pl:
    file: lib/Publican/Localise.pm
  Publican::Localise::pt:
    file: lib/Publican/Localise.pm
  Publican::Localise::pt_br:
    file: lib/Publican/Localise.pm
  Publican::Localise::ru:
    file: lib/Publican/Localise.pm
  Publican::Localise::sk:
    file: lib/Publican/Localise.pm
  Publican::Localise::sr:
    file: lib/Publican/Localise.pm
  Publican::Localise::sr_latn:
    file: lib/Publican/Localise.pm
  Publican::Localise::sv:
    file: lib/Publican/Localise.pm
  Publican::Localise::ta:
    file: lib/Publican/Localise.pm
  Publican::Localise::te:
    file: lib/Publican/Localise.pm
  Publican::Localise::uk:
    file: lib/Publican/Localise.pm
  Publican::Localise::zh_cn:
    file: lib/Publican/Localise.pm
  Publican::Localise::zh_tw:
    file: lib/Publican/Localise.pm
  Publican::Translate:
    file: lib/Publican/Translate.pm
    version: 0.2
  Publican::TreeView:
    file: lib/Publican/TreeView.pm
    version: 0.1
  Publican::WebSite:
    file: lib/Publican/WebSite.pm
    version: 1.3
  Publican::XmlClean:
    file: lib/Publican/XmlClean.pm
    version: 0.2
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
